spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order-service
    password: mysql
    username: order

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 8081