spring:
  datasource:
    url: jdbc:mysql://localhost:34002/inventory
    username: inventory
    password: user123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  application:
    name: Inventory-Service

server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://Gur:Singh@localhost:8766/eureka

  # Distribution Tracing

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
